Repository JoonheeJeong/baseball, pull requests merged in 2023-06, with the labels that each got.

#20 Feature/#15 implement stadiumservice
  src/main/java/console/BaseBallService.java
  src/main/java/console/CommandMapper/RegisterOutPlayerCommandMapper.java
  src/main/java/console/CommandMapper/RegisterPlayerCommandMapper.java
  src/main/java/console/CommandMapper/RegisterStadiumCommandMapper.java
  src/main/java/console/CommandMapper/RegisterTeamCommandMapper.java
  src/main/java/console/CommandMapper/ShowOutPlayerCommandMapper.java
  src/main/java/console/CommandMapper/ShowPlayerCommandMapper.java
  src/main/java/console/CommandMapper/ShowPositionPlayerCommandMapper.java
  src/main/java/console/CommandMapper/ShowStadiumCommandMapper.java
  src/main/java/console/CommandMapper/ShowTeamCommandMapper.java
  src/main/java/console/Menu.java
  src/main/java/service/BaseBallService.java
  src/main/java/service/StadiumService.java
  src/test/java/service/StadiumServiceTest.java
Labels: enhancement

#22 Feature/#21 implement team service
  src/main/java/console/CommandMapper/RegisterTeamCommandMapper.java
  src/main/java/console/CommandMapper/ShowTeamCommandMapper.java
  src/main/java/console/Menu.java
  src/main/java/dao/AbstractMybatisDao.java
  src/main/java/dao/TeamDao.java
  src/main/java/dto/TeamResponseDTO.java
  src/main/java/mapper/TeamMapper.java
  src/main/java/service/StadiumService.java
  src/main/java/service/TeamService.java
  src/main/resources/mapper/TeamMapper.xml
  src/test/java/dao/TeamDaoTest.java
Labels: enhancement

#26 Feature/#11 player dao
  src/main/java/dao/PlayerDao.java
  src/main/java/domain/Player.java
  src/main/java/domain/Position.java
  src/main/java/domain/PositionHandler.java
  src/main/java/exception/IllegalPositionDescriptionException.java
  src/main/java/mapper/PlayerMapper.java
  src/main/resources/db/data.sql
  src/main/resources/mapper/PlayerMapper.xml
  src/main/resources/mapper/mybatis-config.xml
  src/test/java/dao/PlayerDaoTest.java
Labels: enhancement

#32 Feature/#24 refactor reflection
  src/main/java/BaseBallApp.java
  src/main/java/console/CommandMapper/CommandMapper.java
  src/main/java/console/CommandMapper/RegisterOutPlayerCommandMapper.java
  src/main/java/console/CommandMapper/RegisterPlayerCommandMapper.java
  src/main/java/console/CommandMapper/RegisterStadiumCommandMapper.java
  src/main/java/console/CommandMapper/RegisterTeamCommandMapper.java
  src/main/java/console/CommandMapper/ShowOutPlayerCommandMapper.java
  src/main/java/console/CommandMapper/ShowPlayerCommandMapper.java
  src/main/java/console/CommandMapper/ShowPositionPlayerCommandMapper.java
  src/main/java/console/CommandMapper/ShowStadiumCommandMapper.java
  src/main/java/console/CommandMapper/ShowTeamCommandMapper.java
  src/main/java/console/Menu.java
  src/main/java/controller/BaseballController.java
  src/main/java/controller/OutPlayerController.java
  src/main/java/controller/PlayerController.java
  src/main/java/controller/StadiumController.java
  src/main/java/controller/TeamController.java
  src/main/java/dao/OutPlayerDao.java
  src/main/java/dao/PlayerDao.java
  src/main/java/dao/StadiumDao.java
  src/main/java/dao/TeamDao.java
  src/main/java/domain/Reason.java
  src/main/java/domain/ReasonHandler.java
  src/main/java/dto/OutPlayerResponseDTO.java
  src/main/java/exception/IllegalReasonDescriptionException.java
  src/main/java/mapper/OutPlayerMapper.java
  src/main/java/service/BaseBallService.java
  src/main/java/service/OutPlayerService.java
  src/main/java/service/PlayerService.java
  src/main/java/service/StadiumService.java
  src/main/java/service/TeamService.java
  src/main/java/util/ConsoleScanner.java
  src/main/java/util/annotation/Component.java
  src/main/java/util/annotation/Controller.java
  src/main/java/util/annotation/RequestMapping.java
  src/main/java/util/annotation/Service.java
  src/main/resources/db/table.sql
  src/main/resources/mapper/OutPlayerMapper.xml
  src/main/resources/mapper/PlayerMapper.xml
  src/main/resources/mapper/mybatis-config.xml
  src/test/java/service/StadiumServiceTest.java
Labels: enhancement, modification

#35 Feature/#24 refactor exception
  src/main/java/controller/BaseballController.java
  src/main/java/controller/OutPlayerController.java
  src/main/java/controller/PlayerController.java
  src/main/java/controller/StadiumController.java
  src/main/java/controller/TeamController.java
  src/main/java/dao/OutPlayerDao.java
  src/main/java/dao/PlayerDao.java
  src/main/java/dao/StadiumDao.java
  src/main/java/dao/TeamDao.java
  src/main/java/exception/IllegalCommandException.java
  src/main/java/exception/IllegalParameterException.java
  src/main/java/exception/IllegalReasonDescriptionException.java
  src/main/java/exception/IllegalRequestTypeException.java
  src/main/java/service/OutPlayerService.java
  src/main/java/service/PlayerService.java
  src/main/java/service/StadiumService.java
  src/main/java/service/TeamService.java
  src/main/java/util/ConsoleScanner.java
  src/main/java/util/messages/ErrorMessage.java
  src/main/java/util/messages/ResponseMessage.java
  src/test/java/service/StadiumServiceTest.java
Labels: modification

#36 modify #25 - database, table
  build.gradle
  src/main/java/dao/PlayerDao.java
  src/main/java/domain/PositionHandler.java
  src/main/java/dto/PositionTeamPlayerDto.java
  src/main/java/mapper/PlayerMapper.java
  src/main/resources/db/data.sql
  src/main/resources/db/dcl.sql
  src/main/resources/db/procedure.sql
  src/main/resources/db/query_ref.sql
  src/main/resources/db/table.sql
  src/main/resources/db/view.sql
  src/main/resources/mapper/OutPlayerMapper.xml
  src/main/resources/mapper/PlayerMapper.xml
  src/main/resources/mapper/TeamMapper.xml
  src/main/resources/mapper/db.properties
  src/test/java/dao/PlayerDaoTest.java
  src/test/java/dao/TeamDaoTest.java
Labels: enhancement, modification

#38 Feature/#25 player dao select list for each team by position
  src/main/java/dao/PlayerDao.java
  src/main/java/domain/PositionTeamPlayer.java
  src/main/java/domain/TeamName.java
  src/main/java/dto/PositionTeamPlayerDto.java
  src/main/java/mapper/PlayerMapper.java
  src/main/resources/db/data.sql
  src/main/resources/db/table.sql
  src/main/resources/db/view.sql
  src/test/java/dao/PlayerDaoTest.java
Labels: enhancement, modification

#39 Feature/#31 player dao update retired by
  src/main/java/dao/PlayerDao.java
  src/main/java/mapper/PlayerMapper.java
  src/main/resources/mapper/PlayerMapper.xml
  src/test/java/dao/PlayerDaoTest.java
Labels: enhancement

#41 Fix/#25 player dao select list for each team by position
  src/main/java/dao/PlayerDao.java
  src/test/java/dao/PlayerDaoTest.java
Labels: bug

#45 fix #37 - exception handler of ConsoleScanner
  src/main/java/util/ConsoleScanner.java
Labels: bug

#48 main의 Readme를 develop으로 가져옵니다.
  README.md
Labels: documentation

#49 Refactor/#24 sql session factory
  src/main/java/service/BaseBallService.java
  src/main/java/service/OutPlayerService.java
  src/main/java/service/PlayerService.java
  src/main/java/service/StadiumService.java
  src/main/java/service/TeamService.java
  src/main/java/util/SqlSessionFactoryUtil.java
  src/test/java/dao/PlayerDaoTest.java
  src/test/java/dao/SqlSessionFactoryUtil.java
  src/test/java/dao/StadiumDaoTest.java
  src/test/java/dao/TeamDaoTest.java
Labels: refactor

#51 Refactor/#24 console scanner
  src/main/java/controller/BaseballController.java
  src/main/java/controller/OutPlayerController.java
  src/main/java/controller/PlayerController.java
  src/main/java/controller/StadiumController.java
  src/main/java/controller/TeamController.java
  src/main/java/util/Assembler.java
  src/main/java/util/ConsoleScanner.java
Labels: refactor

#53 fix #43 - transaction logic for OutPlayer register
  src/main/java/service/OutPlayerService.java
Labels: bug

#54 rename dto
  src/main/java/dao/OutPlayerDao.java
  src/main/java/dao/TeamDao.java
  src/main/java/dto/OutPlayerResponseDto.java
  src/main/java/dto/TeamResponseDto.java
  src/main/java/mapper/OutPlayerMapper.java
  src/main/java/mapper/TeamMapper.java
  src/main/java/service/OutPlayerService.java
  src/main/java/service/TeamService.java
  src/main/resources/mapper/OutPlayerMapper.xml
  src/main/resources/mapper/TeamMapper.xml
Labels: refactor

#57 Develop
  src/main/java/dao/OutPlayerDao.java
  src/main/java/dao/TeamDao.java
  src/main/java/dto/OutPlayerResponseDto.java
  src/main/java/dto/TeamResponseDto.java
  src/main/java/mapper/OutPlayerMapper.java
  src/main/java/mapper/TeamMapper.java
  src/main/java/service/OutPlayerService.java
  src/main/java/service/TeamService.java
  src/main/resources/mapper/OutPlayerMapper.xml
  src/main/resources/mapper/TeamMapper.xml
  src/test/java/dao/TeamDaoTest.java
Labels: refactor
